#!/bin/sh
uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="en"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

uci set luci.main.lang='en'
uci commit luci

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"
ln -sf "/sbin/ip" "/usr/bin/ip"

uci set luci.themes.Argon="/luci-static/argon"
uci set luci.main.mediaurlbase="/luci-static/argon"
uci commit luci

uci set system.@system[0].hostname='DOTYCAT'
uci commit system

uci set system.@system[0].timezone='+08'
uci set system.@system[0].zonename='Asia/Kuala_Lumpur'
uci commit system

uci set network.lan.ipaddr='192.168.1.1'
uci commit network

uci set wireless.@wifi-device[0].disabled='0'
[ -z "$(uci get wireless.@wifi-iface[0].ssid 2>/dev/null)" ] && wifi config
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].ssid='DOTYCAT'
uci set wireless.@wifi-iface[0].encryption='none'
uci delete wireless.@wifi-iface[0].key
uci commit wireless
wifi reload

uci set network.lan.dns='8.8.8.8 8.8.4.4'
uci set network.lan.peerdns='0'
uci commit network

opkg remove luci-i18n-base-zh-cn 2>/dev/null
opkg list-installed | grep -E 'luci-i18n-.*-zh-cn' | cut -f1 -d' ' | xargs -r opkg remove

rm -f /etc/banner
cat << "EOF" > /etc/banner
 (        )            )                            )    *     
 )\ )  ( /(   *   ) ( /(   (    (      *   )  (  ( /(  (  `    
(()/(  )\())` )  /( )\())  )\   )\   ` )  /(  )\ )\()) )\))(   
 /(_))((_)\  ( )(_)|(_)\ (((_|(((_)(  ( )(_)|((_|(_)\ ((_)()\  
(_))_   ((_)(_(_())_ ((_))\___)\ _ )\(_(_()))\___ ((_)(_()((_) 
 |   \ / _ \|_   _\ \ / ((/ __(_)_\(_)_   _((/ __/ _ \|  \/  | 
 | |) | (_) | | |  \ V / | (__ / _ \   | |_ | (_| (_) | |\/| | 
 |___/ \___/  |_|   |_|   \___/_/ \_\  |_(_) \___\___/|_|  |_| 
                                                               
EOF

exit 0
