#!/bin/sh
uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

uci set luci.main.lang='en'
uci commit luci

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"
ln -sf "/sbin/ip" "/usr/bin/ip"

uci set luci.themes.Argon="/luci-static/argon"
uci set luci.main.mediaurlbase="/luci-static/argon"
uci commit luci

uci set system.@system[0].hostname='DOTYCAT'
uci commit system

uci set system.@system[0].timezone='+08'
uci set system.@system[0].zonename='Asia/Kuala_Lumpur'
uci commit system

uci set network.lan.ipaddr='192.168.1.1'
uci commit network

uci set wireless.@wifi-device[0].disabled='0'
[ -z "$(uci get wireless.@wifi-iface[0].ssid 2>/dev/null)" ] && wifi config
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].ssid='DOTYCAT'
uci set wireless.@wifi-iface[0].encryption='none'
uci delete wireless.@wifi-iface[0].key
uci commit wireless
wifi reload

uci set network.lan.dns='8.8.8.8 8.8.4.4'
uci set network.lan.peerdns='0'
uci commit network

cat << "EOF" > /etc/banner
  ___  ____  ____  ____  ____ 
 / __)(  _ \(  _ \( ___)(  _ \
( (__  )   / )___/ )__)  )   /
 \___)(_)\_)(__)  (____)(_)\_)

 Welcome to My Custom OpenWrt Build!
 WiFi: DOTYCAT (Open Network)
 Timezone: Asia/Kuala_Lumpur
 LAN IP: 192.168.1.1
EOF

exit 0
