#!/bin/sh

# Avoid duplicate execution
uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

# Disable dnsmasq logging
sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

# Symlink for 'ip' command
ln -sf "/sbin/ip" "/usr/bin/ip"

# LuCI theme: Argon
uci set luci.themes.Argon="/luci-static/argon"
uci set luci.main.mediaurlbase="/luci-static/argon"
uci commit luci

# Hostname
uci set system.@system[0].hostname='DOTYCAT'
uci commit system

# Timezone: Malaysia
uci set system.@system[0].timezone='+08'
uci set system.@system[0].zonename='Asia/Kuala_Lumpur'
uci commit system

# Clear root password
sed -i '/^root::/d' /etc/shadow

# LAN IP: 192.168.1.1
uci set network.lan.ipaddr='192.168.1.1'
uci commit network

# Enable WiFi
uci set wireless.@wifi-device[0].disabled='0'

# WiFi Settings: SSID DOTYCAT, no password (open network)
uci set wireless.@wifi-iface[0].ssid='DOTYCAT'
uci set wireless.@wifi-iface[0].encryption='none'
uci delete wireless.@wifi-iface[0].key
uci commit wireless

# DNS
uci set network.lan.dns='8.8.8.8 8.8.4.4'
uci set network.lan.peerdns='0'
uci commit network

# Disable IPv6
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ndp='disabled'
uci commit dhcp

# Custom banner
cat << "EOF" > /etc/banner
  ___  ____  ____  ____  ____ 
 / __)(  _ \(  _ \( ___)(  _ \
( (__  )   / )___/ )__)  )   /
 \___)(_)\_)(__)  (____)(_)\_)

 Welcome to My Custom OpenWrt Build!
 WiFi: DOTYCAT (Open Network)
 Timezone: Asia/Kuala_Lumpur
 LAN IP: 192.168.1.1
EOF

exit 0
